development:
  url: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:b3b48726316373fc2297bd1f171449af@soldierfish.redistogo.com:11003/
  channel_prefix: Dissonance_production
